### ISSUE TITLE
No symlinks are created at all in the shortix folder

### ISSUE THREAD

**Issue by Proaxel** [Jannomag/shortix#9]
Tried:
- running the update script several times and selecting different options
- restarting the Deck. 

Screenshot is what the folder looks like after running the update script
![image](https://github.com/user-attachments/assets/13cb0bb0-8458-4c74-b837-7e740c556f7c)

**Comment by Proaxel** [comment]
Nevermind I'm a dummy. I forgot to reinstall Protontricks after I uninstalled it in order to troubleshoot an unrelated issue.

Though perhaps this can rehashed as a feature suggestion? Add some sort of ProtonTricks installation detection and display a warning message if it doesn't detect it.

**Comment by Jannomag** [comment]
The script should check the presence of protontricks already (lines 16-22 in Shortix.sh).

So now I'm wondering why it didn't work when you didn't have Protontricks installed

**Comment by Proaxel** [comment]
> The script should check the presence of protontricks already (lines 16-22 in Shortix.sh).
> 
> So now I'm wondering why it didn't work when you didn't have Protontricks installed

(Apologies, I wasn't expecting any reply)
Was there supposed to be some sort of error message when installing or updating? I didn't get any, just the usual yes/no setup popups and then update complete message... If you're willing to investigate, I'm willing to test any debug stuff you send me

**Comment by Jannomag** [comment]
When I find some time I will try it in a VM and check if the script ignores missing proton because of the ui popups. If I need some more testing I’ll let you know Am 09.11.2024 um 00:37 schrieb Proaxel ***@***.***>:﻿

The script should check the presence of protontricks already (lines 16-22 in Shortix.sh).
So now I'm wondering why it didn't work when you didn't have Protontricks installed

(Apologies, I wasn't expecting any reply)
Was there supposed to be some sort of error message when installing or updating? I didn't get any, just the usual yes/no setup popups and then update complete message... If you're willing to investigate, I'm willing to test any debug stuff you send me

**Comment by Jannomag** [comment]
I updated Shortix. It should now check if Protontricks is installed correctly. The issue was my code which wasn't working when checking for flatpak. The command I was using always had a "true" output because the `flatpak run` has an output even if it's an error. I modified the if argument. It should work now and display an error.
I also added a fallback dialog method when kdialog is not installed, since I tested it on Gnome first. So even on systems with kdialog Shortix will work no.

If you can test it I would like to know following:
- Remove the Shortix directory completely
- Remove the desktop shortcut completely
Then:
- Install Shortix following the readme.

- Remove protontricks again, both native and flatpak and try shortix again (completely)
- Remove kdialog using Pacman and check if the installer / updater work
- Try with protontricks from yay only
- Try with protontricks flatpak only

Thannks in advance!

**Comment by Proaxel** [comment]
Okay I said no to add Shortix's update service, and deleted Shortix's folder, installer and Update items, uninstalled ProtonTricks with the Discover store. I downloaded a fresh new installer, and I got the error immediately. Installed ProtonTricks through Discover, ran the Shortix installer again and it worked. Thanks for your work.

As much as I would like to test the rest, I'm a Linux newb... I tried installing yay and it gives me an error about it not finding fakeroot. I google search, find a command that should fix it, but then THAT gave me a couple of errors... I decided to leave it there before I break something trying to follow random stuff I'm not knowledgeable about online.

If you're willing to tell me the exact steps, commands, etc on how to perform these steps off on a sort-of-fresh Steam Deck, I'm willing to do them

**Comment by Jannomag** [comment]
That's enough then. Installing yay on SteamOS is a bit different since it's a readonly filesystem. I tried it in EndeavourOS and it worked for me - but it is how it is, even if I test it, it doesn't mean it works 😅

I'm glad that the error was shown without the flatpak.

Thank you very much for mentioning and testing!
